sudo: required
services:
  - docker

before_install: 
  - docker build -t subhadeep/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run subhadeep/react-test npm test -- ----coverage

after_success: 
  - docker build -t subhadeep/multi-client ./client
  - docker build -t subhadeep/multi-nginx ./nginx
  - docker build -t subhadeep/multi-server ./server
  - docker build -t subhadeep/multi-worker ./worker
